In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6] # arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr[:] = 99

In [13]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
arr  # slices create a reference to the original array and therefore overwrite on assignment

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()

In [16]:
arr_copy[:] = 100

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_2d = np.arange(5,50,5)

In [23]:
arr_2d = arr_2d.reshape(3,3)

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[0][0]   # double bracket notation

5

In [26]:
arr_2d[0]

array([ 5, 10, 15])

In [27]:
arr_2d[2,1]  # single bracket notation

40

In [28]:
arr_2d[:2,1:]  # slice notation

array([[10, 15],
       [25, 30]])

In [29]:
# conditional selection

In [31]:
arr = np.arange(1,11)

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [34]:
bool_arrr = arr > 5

In [36]:
bool_arr

NameError: name 'bool_arr' is not defined